#Conversion of images to array's

##Black and White Image

In [1]:
from PIL import Image
import numpy as np

# Load the black and white image
image = Image.open('images.jpg').convert('L')  # 'L' mode ensures grayscale

# Convert the image to a NumPy 2D array
image_array = np.array(image)

# Print or check the 2D array
print(image_array)


[[212 213 216 ... 107 106 106]
 [210 212 214 ... 104 104 103]
 [207 209 211 ... 100 100  99]
 ...
 [ 13  13  14 ...  36  36  36]
 [ 13  13  13 ...  39  38  36]
 [ 12  12  13 ...  39  37  34]]


##Coloured Image

In [7]:
from PIL import Image
import numpy as np

# Load the black and white image
image = Image.open('images1.jpg')

# Convert the image to a NumPy 3D array
image_array = np.array(image)

# Print or check the 3D array
print(image_array)


[[[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 2  7 26]
  [ 2  7 26]
  [ 2  7 26]]

 [[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 2  7 26]
  [ 2  7 26]
  [ 2  7 26]]

 [[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 2  7 26]
  [ 2  7 26]
  [ 2  7 26]]

 ...

 [[ 2  2  0]
  [ 5  5  3]
  [10 11  6]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 [[ 2  2  0]
  [ 5  5  3]
  [10 11  6]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 [[ 2  2  0]
  [ 5  5  3]
  [10 11  6]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]]
